name = "authentication"
version = "0.1.0"
defaultTargets = ["Authentication"]
testDriver = "tests"

[[require]]
name = "leansqlite"
git = "https://github.com/leanprover/leansqlite"
rev = "v4.33.0"

[[require]]
name = "leanpostgres"
git = "https://github.com/paulbutcher/leanpostgres"
rev = "v0.4.0"

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
warningAsError = true

[[lean_lib]]
name = "Authentication"

[[lean_lib]]
name = "AuthenticationSql"

[[lean_lib]]
name = "AuthenticationSqlite"

[[lean_lib]]
name = "AuthenticationPostgres"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "tests"
root = "Tests.Main"
